{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Falhas de checkout",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(checkout_order_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\nsum(increase(checkout_order_failures_total[$__rate_interval]))\r\n/\r\nclamp_min(\r\n  sum(increase(checkout_orders_total[$__rate_interval]))\r\n  + sum(increase(checkout_order_failures_total[$__rate_interval])),\r\n  1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duração pagamento p95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(checkout_payment_duration_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duração pagamento p99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(checkout_payment_duration_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Falhas por motivo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (reason, reason_description) (increase(checkout_order_failures_total[$__rate_interval]))",
     "legendFormat": "{{reason_description}} ({{reason}})"
    }
   ]
  },
  {
   "title": "Place Order - Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "operation": "checkout.place_order", "service": "unknown_service:Nop.Web", "tags": "checkout.success=true" }
   ]
  },
  {
   "title": "Place Order - Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "operation": "checkout.place_order", "service": "unknown_service:Nop.Web", "tags": "checkout.success=false" }
   ]
  },
  {
   "title": "Pedidos com sucesso",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(checkout_orders_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pedidos por intervalo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(checkout_orders_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}